// Generated by scripts/generate-mcp-catalog.ts from the servers registry.
// Holds secret NAMES only (headers, variables, where to look); never a value.
import type { CatalogEntry } from "./mcp-catalog.ts";

export const BUILTIN_MCP_CATALOG: CatalogEntry[] = [
  {
    "name": "gateway",
    "label": "Gateway tools",
    "description": "Docs lookup, reasoning, databases, Stripe, meetings, notes and Figma frames through the LiteLLM gateway.",
    "transport": "http",
    "url": "http://10.69.42.110:4100/mcp",
    "headers": {
      "x-mcp-servers": "context7,sequential_thinking,postgres_legacy,postgres_v2,fetch,obsidian_vault,stripe_aetherkey,gsd_meetings,figma_framelink"
    },
    "secrets": [
      {
        "target": "header",
        "name": "x-litellm-api-key",
        "envKey": "MCP_GATEWAY_KEY"
      }
    ]
  },
  {
    "name": "affine",
    "label": "AFFiNE",
    "description": "Read and edit documents in the AFFiNE wiki.",
    "transport": "http",
    "url": "http://10.69.42.110:4100/mcp",
    "headers": {
      "x-mcp-servers": "affine"
    },
    "secrets": [
      {
        "target": "header",
        "name": "x-litellm-api-key",
        "envKey": "MCP_GATEWAY_KEY"
      }
    ]
  },
  {
    "name": "grafana",
    "label": "Grafana",
    "description": "Dashboards, Loki logs and Prometheus metrics.",
    "transport": "http",
    "url": "http://10.69.42.110:4100/mcp",
    "headers": {
      "x-mcp-servers": "grafana"
    },
    "secrets": [
      {
        "target": "header",
        "name": "x-litellm-api-key",
        "envKey": "MCP_GATEWAY_KEY"
      }
    ]
  },
  {
    "name": "asana",
    "label": "Asana",
    "description": "Projects, tasks and comments in Asana.",
    "transport": "http",
    "url": "http://10.69.42.110:4100/mcp",
    "headers": {
      "x-mcp-servers": "asana"
    },
    "secrets": [
      {
        "target": "header",
        "name": "x-litellm-api-key",
        "envKey": "MCP_GATEWAY_KEY"
      }
    ]
  },
  {
    "name": "hindsight",
    "label": "Hindsight",
    "description": "Retain and recall work and technical memory.",
    "transport": "http",
    "url": "http://10.69.42.110:4100/mcp",
    "headers": {
      "x-mcp-servers": "hindsight"
    },
    "secrets": [
      {
        "target": "header",
        "name": "x-litellm-api-key",
        "envKey": "MCP_GATEWAY_KEY"
      }
    ]
  },
  {
    "name": "honcho",
    "label": "Honcho",
    "description": "Long-term memory about the user.",
    "transport": "http",
    "url": "http://10.69.42.110:4100/mcp",
    "headers": {
      "x-mcp-servers": "honcho"
    },
    "secrets": [
      {
        "target": "header",
        "name": "x-litellm-api-key",
        "envKey": "MCP_GATEWAY_KEY"
      }
    ]
  },
  {
    "name": "slack-jump",
    "label": "Slack · Jump",
    "description": "Read and post in the Jump Slack workspace.",
    "transport": "http",
    "url": "http://10.69.42.110:4100/mcp",
    "headers": {
      "x-mcp-servers": "slack_jump"
    },
    "secrets": [
      {
        "target": "header",
        "name": "x-litellm-api-key",
        "envKey": "MCP_GATEWAY_KEY"
      }
    ]
  },
  {
    "name": "slack-gsd",
    "label": "Slack · GSD",
    "description": "Read and post in the GSD Slack workspace.",
    "transport": "http",
    "url": "http://10.69.42.110:4100/mcp",
    "headers": {
      "x-mcp-servers": "slack_gsd"
    },
    "secrets": [
      {
        "target": "header",
        "name": "x-litellm-api-key",
        "envKey": "MCP_GATEWAY_KEY"
      }
    ]
  },
  {
    "name": "slack-feltright",
    "label": "Slack · Felt Right",
    "description": "Read and post in the Felt Right Slack workspace.",
    "transport": "http",
    "url": "http://10.69.42.110:4100/mcp",
    "headers": {
      "x-mcp-servers": "slack_feltright"
    },
    "secrets": [
      {
        "target": "header",
        "name": "x-litellm-api-key",
        "envKey": "MCP_GATEWAY_KEY"
      }
    ]
  },
  {
    "name": "fireflies-gw",
    "label": "Fireflies",
    "description": "Meeting transcripts and summaries through the gateway.",
    "transport": "http",
    "url": "http://10.69.42.110:4100/mcp",
    "headers": {
      "x-mcp-servers": "fireflies"
    },
    "secrets": [
      {
        "target": "header",
        "name": "x-litellm-api-key",
        "envKey": "MCP_GATEWAY_KEY"
      }
    ]
  },
  {
    "name": "mobbin",
    "label": "Mobbin",
    "description": "Search app screens and flows for design reference.",
    "transport": "http",
    "url": "http://10.69.42.110:4100/mcp",
    "headers": {
      "x-mcp-servers": "mobbin"
    },
    "secrets": [
      {
        "target": "header",
        "name": "x-litellm-api-key",
        "envKey": "MCP_GATEWAY_KEY"
      }
    ]
  },
  {
    "name": "figma",
    "label": "Figma",
    "description": "Read designs and components from Figma.",
    "transport": "http",
    "url": "https://mcp.figma.com/mcp",
    "secrets": []
  },
  {
    "name": "filesystem",
    "label": "Filesystem",
    "description": "Read and write files in the shared workspace folders.",
    "transport": "stdio",
    "command": "/home/clauber/.npm-global/bin/mcp-server-filesystem",
    "args": [
      "/workspace/projects",
      "/workspace/ai"
    ],
    "secrets": []
  },
  {
    "name": "serena",
    "label": "Serena",
    "description": "Symbol-level code search and editing.",
    "transport": "stdio",
    "command": "uvx",
    "args": [
      "--from",
      "git+https://github.com/oraios/serena",
      "serena",
      "start-mcp-server",
      "--context",
      "ide-assistant"
    ],
    "secrets": []
  },
  {
    "name": "kero-inbox",
    "label": "Kero inbox",
    "description": "Message Kero, the ChatGPT assistant, and read replies.",
    "transport": "http",
    "url": "http://10.69.42.110:4100/mcp",
    "headers": {
      "x-mcp-servers": "kero_inbox_claude_code"
    },
    "secrets": [
      {
        "target": "header",
        "name": "x-litellm-api-key",
        "envKey": "KERO_INBOX_KEY_CLAUDE_CODE"
      }
    ]
  },
  {
    "name": "agent-dispatch",
    "label": "Agent dispatch",
    "description": "Route work to another agent and run headless sessions.",
    "transport": "stdio",
    "command": "/workspace/ai/mcp/agent-dispatch-mcp.py",
    "args": [],
    "secrets": []
  },
  {
    "name": "ssh-vps",
    "label": "SSH hosts",
    "description": "Run commands and read files on the configured VPS hosts.",
    "transport": "stdio",
    "command": "/workspace/ai/mcp/ssh-vps.py",
    "args": [],
    "secrets": []
  },
  {
    "name": "gog",
    "label": "Gmail & Calendar",
    "description": "Search and read Gmail, list Calendar events (default account) through the gog gateway.",
    "transport": "http",
    "url": "http://10.69.42.110:4000/mcp",
    "headers": {
      "x-mcp-servers": "gog"
    },
    "secrets": [
      {
        "target": "header",
        "name": "x-litellm-api-key",
        "envKey": "GOG_GATEWAY_KEY"
      }
    ]
  },
  {
    "name": "gog-clauber93",
    "label": "Gmail & Calendar · clauber93",
    "description": "Gmail and Calendar for the clauber93 account through the gog gateway.",
    "transport": "http",
    "url": "http://10.69.42.110:4000/mcp",
    "headers": {
      "x-mcp-servers": "gog_clauber93"
    },
    "secrets": [
      {
        "target": "header",
        "name": "x-litellm-api-key",
        "envKey": "GOG_GATEWAY_KEY"
      }
    ]
  },
  {
    "name": "gog-cklauber",
    "label": "Gmail & Calendar · cklauber",
    "description": "Gmail and Calendar for the cklauber account through the gog gateway.",
    "transport": "http",
    "url": "http://10.69.42.110:4000/mcp",
    "headers": {
      "x-mcp-servers": "gog_cklauber"
    },
    "secrets": [
      {
        "target": "header",
        "name": "x-litellm-api-key",
        "envKey": "GOG_GATEWAY_KEY"
      }
    ]
  },
  {
    "name": "t3",
    "label": "T3 Code",
    "description": "Orchestrate T3 Code threads and projects on this machine.",
    "transport": "http",
    "url": "http://127.0.0.1:3773/mcp",
    "secrets": [
      {
        "target": "header",
        "name": "Authorization"
      }
    ]
  }
];
