#!/usr/bin/env -S node --experimental-strip-types
// Regenerates server/mcp-catalog-data.ts from a servers registry
// (default /workspace/ai/mcp/servers.json). The registry holds live
// credentials; this script reads them only to find which environment
// variable carries each one, and writes that variable's NAME. No value is
// printed or written.
//
//   node --experimental-strip-types scripts/generate-mcp-catalog.ts [registry.json]
import { readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { parseRegistry, type RegistryMeta } from "../server/mcp-catalog.ts";

const registryPath = process.argv[2] ?? "/workspace/ai/mcp/servers.json";
const OUT = fileURLToPath(new URL("../server/mcp-catalog-data.ts", import.meta.url));

const META: Record<string, RegistryMeta> = {
  gateway: { label: "Gateway tools", description: "Docs lookup, reasoning, databases, Stripe, meetings, notes and Figma frames through the LiteLLM gateway." },
  affine: { label: "AFFiNE", description: "Read and edit documents in the AFFiNE wiki." },
  grafana: { label: "Grafana", description: "Dashboards, Loki logs and Prometheus metrics." },
  asana: { label: "Asana", description: "Projects, tasks and comments in Asana." },
  hindsight: { label: "Hindsight", description: "Retain and recall work and technical memory." },
  honcho: { label: "Honcho", description: "Long-term memory about the user." },
  "slack-jump": { label: "Slack · Jump", description: "Read and post in the Jump Slack workspace." },
  "slack-gsd": { label: "Slack · GSD", description: "Read and post in the GSD Slack workspace." },
  "slack-feltright": { label: "Slack · Felt Right", description: "Read and post in the Felt Right Slack workspace." },
  "fireflies-gw": { label: "Fireflies", description: "Meeting transcripts and summaries through the gateway." },
  mobbin: { label: "Mobbin", description: "Search app screens and flows for design reference." },
  figma: { label: "Figma", description: "Read designs and components from Figma." },
  filesystem: { label: "Filesystem", description: "Read and write files in the shared workspace folders." },
  serena: { label: "Serena", description: "Symbol-level code search and editing." },
  "kero-inbox": { label: "Kero inbox", description: "Message Kero, the ChatGPT assistant, and read replies." },
  "agent-dispatch": { label: "Agent dispatch", description: "Route work to another agent and run headless sessions." },
  "ssh-vps": { label: "SSH hosts", description: "Run commands and read files on the configured VPS hosts." },
  gog: { label: "Gmail & Calendar", description: "Search and read Gmail, list Calendar events (default account) through the gog gateway." },
  "gog-clauber93": { label: "Gmail & Calendar · clauber93", description: "Gmail and Calendar for the clauber93 account through the gog gateway." },
  "gog-cklauber": { label: "Gmail & Calendar · cklauber", description: "Gmail and Calendar for the cklauber account through the gog gateway." },
  t3: { label: "T3 Code", description: "Orchestrate T3 Code threads and projects on this machine." },
};

// Slots whose value is not in any env file yet get a stable name to put it in.
const FALLBACK_KEYS: Record<string, string> = {
  "gog/x-litellm-api-key": "GOG_GATEWAY_KEY",
  "gog-clauber93/x-litellm-api-key": "GOG_GATEWAY_KEY",
  "gog-cklauber/x-litellm-api-key": "GOG_GATEWAY_KEY",
};

const registry = JSON.parse(readFileSync(registryPath, "utf8")) as { mcpServers: Record<string, { headers?: Record<string, string>; env?: Record<string, string> }> };
const envByValue = new Map<string, string>();
for (const file of [join(homedir(), "ai/.env"), join(homedir(), ".claude/.env")]) {
  let text = "";
  try { text = readFileSync(file, "utf8"); } catch { continue; }
  for (const line of text.split(/\r?\n/)) {
    const at = line.indexOf("=");
    if (at <= 0 || line.startsWith("#")) continue;
    const value = line.slice(at + 1).trim().replace(/^(["'])(.*)\1$/, "$2");
    const key = line.slice(0, at);
    if (value && !envByValue.has(value)) envByValue.set(value, key);
  }
}
const envKeyHints: Record<string, string> = { ...FALLBACK_KEYS };
for (const [name, server] of Object.entries(registry.mcpServers)) {
  for (const group of [server.headers, server.env]) {
    for (const [slot, value] of Object.entries(group ?? {})) {
      const bare = value.replace(/^Bearer\s+/i, "");
      const key = envByValue.get(value) ?? envByValue.get(bare);
      if (key) envKeyHints[`${name}/${slot}`] = key;
    }
  }
}

const { entries, skipped } = parseRegistry(registry, { meta: META, envKeyHints });
const body = `// Generated by scripts/generate-mcp-catalog.ts from the servers registry.
// Holds secret NAMES only (headers, variables, where to look); never a value.
import type { CatalogEntry } from "./mcp-catalog.ts";

export const BUILTIN_MCP_CATALOG: CatalogEntry[] = ${JSON.stringify(entries, null, 2)};
`;
writeFileSync(OUT, body);
console.log(`wrote ${entries.length} entries to ${OUT}`);
for (const skip of skipped) console.log(`skipped ${skip.name}: ${skip.reason}`);
