import { spawn, type ChildProcess } from "node:child_process";
import { createHmac } from "node:crypto";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { afterAll, expect, it } from "vitest";
import { resolveAgentBrowserBinary } from "../../server/browser-engine.ts";
import { waitForExit } from "../../server/testing/cleanup.ts";
import { runControlOmb } from "../control-omb.ts";
import { UI_TOOLS_DIR } from "./control-omb-ui.ts";

const ROOT = fileURLToPath(new URL("../..", import.meta.url));
const enabled = process.env.OMB_UI_E2E === "1" || Boolean(resolveAgentBrowserBinary({ dataDir: UI_TOOLS_DIR, env: process.env }));
let child: ChildProcess | undefined;
afterAll(() => waitForExit(child, { signal: "SIGINT", graceMs: 30_000 }));
(enabled ? it : it.skip)("creates, signs and edits a GitHub routine through the real renderer without redisplaying its secret", async () => {
  let output = "", stderr = "";
  child = spawn(process.execPath, ["--experimental-strip-types", join(ROOT, "scripts/control-omb.ts"), "ui", "launch"], { cwd: ROOT, env: process.env, stdio: ["ignore", "pipe", "pipe"] });
  child.stdout!.on("data", chunk => { output += String(chunk); });
  child.stderr!.on("data", chunk => { stderr += String(chunk); });
  let fixture!: { ui: string; url: string; logPath: string };
  await expect.poll(() => {
    if (child!.exitCode !== null) throw new Error(stderr);
    try { fixture = JSON.parse(output); return Boolean(fixture.ui); } catch { return false; }
  }, { timeout: 120_000 }).toBe(true);
  const ui = (verb: string, ...args: string[]) => runControlOmb(["ui", verb, "--ui", fixture.ui, ...args]) as Promise<any>;
  const evaluate = async (js: string) => (await ui("eval", "--js", js)).result;
  const click = async (name: string) => { try { return await ui("click", "--name", name); } catch (error) { throw new Error(`Click ${name}: ${error instanceof Error ? error.message : error}`); } };
  const fill = (selector: string, value: string) => evaluate(`(() => { const field = document.querySelector(${JSON.stringify(selector)}); Object.getOwnPropertyDescriptor(field instanceof HTMLTextAreaElement ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype, 'value').set.call(field, ${JSON.stringify(value)}); field.dispatchEvent(new Event('input', { bubbles: true })); return field.value; })()`);
  const select = (label: string, value: string) => evaluate(`(() => { const field = document.querySelector('select[aria-label=${JSON.stringify(label)}]'); field.value = ${JSON.stringify(value)}; field.dispatchEvent(new Event('change', { bubbles: true })); return field.value; })()`);
  const state = () => fetch(`${fixture.url}/api/routines`).then(response => response.json()) as Promise<any>;
  await click("Routines"); await click("New routine");
  await fill('input[placeholder="Add title"]', "GitHub renderer fixture");
  await fill('textarea[placeholder="What should the bot do?"]', "Summarize only this fixture event.");
  if (!await evaluate('Array.from(document.querySelectorAll("select")).some(el => el.getAttribute("aria-label") === "Routine trigger")')) await click("More options");
  await select("Routine trigger", "github");
  await fill('input[aria-label="GitHub repository"]', "owner/name");
  await evaluate('document.querySelector("fieldset").scrollIntoView({ block: "center" })');
  await click("pull_request");
  await fill('input[aria-label="GitHub actions"]', "opened, merged");
  expect(await evaluate('document.querySelector(\'input[aria-label="GitHub actions"]\').value')).toBe("opened, merged");
  await fill('input[aria-label="GitHub actions"]', "");
  await click("Schedule routine");
  await expect.poll(() => evaluate('Boolean(document.querySelector(\'[aria-label="GitHub routine saved"]\'))')).toBe(true);
  const secret = await evaluate('document.querySelector(\'input[aria-label="GitHub secret"]\').value');
  expect(secret).toMatch(/^[a-f0-9]{64}$/);
  await expect.poll(() => evaluate('document.querySelector(\'input[aria-label="GitHub webhook URL"]\').value')).toContain("/hooks/github/");
  const endpoint = await evaluate('document.querySelector(\'input[aria-label="GitHub webhook URL"]\').value');
  const routine = (await state()).routines.find((r: any) => r.name === "GitHub renderer fixture");
  expect(routine.github).toEqual({ repo: "owner/name", events: ["push", "pull_request"] });
  expect(routine.nextRunAt).toBeNull();
  expect(endpoint).toContain(routine.id);
  await click("Done"); await click("List");
  await expect.poll(() => evaluate("document.body.innerText")).toContain("Listening for GitHub");
  const raw = JSON.stringify({ repository: { full_name: "owner/name" }, sender: { login: "alice" }, ref: "refs/heads/main", commits: [{ message: "Renderer push" }], head_commit: { message: "Renderer push" } });
  const signed = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json", "x-github-event": "push", "x-github-delivery": "renderer-push", "x-hub-signature-256": `sha256=${createHmac("sha256", secret).update(raw).digest("hex")}` }, body: raw });
  expect(signed.status).toBe(200);
  const { runId } = await signed.json() as any;
  await expect.poll(async () => (await state()).runs.find((r: any) => r.id === runId)?.status, { timeout: 30_000 }).toBe("completed");
  await click("Run logs");
  await expect.poll(() => evaluate("document.body.innerText")).toContain("GitHub renderer fixture");
  await ui("screenshot", "--out", `${fixture.logPath}.github-runs.png`);
  await click("List");
  await evaluate('document.querySelector(\'article[aria-label="GitHub renderer fixture"] button\').click()');
  await click("Edit");
  expect(await evaluate('document.querySelector(\'select[aria-label="Routine trigger"]\').value')).toBe("github");
  expect(await evaluate('Boolean(document.querySelector(\'input[aria-label="GitHub secret"]\'))')).toBe(false);
  expect(await evaluate("document.body.innerText")).toContain("The saved secret is hidden.");
  await fill('input[aria-label="GitHub actions"]', "opened, merged");
  await click("Save");
  await expect.poll(async () => (await state()).routines.find((r: any) => r.id === routine.id)?.github.actions).toEqual(["opened", "merged"]);
  await evaluate('document.querySelector(\'article[aria-label="GitHub renderer fixture"] button\').click()');
  await click("Edit");
  expect(await evaluate('document.querySelector(\'input[aria-label="GitHub actions"]\').value')).toBe("opened, merged");
  expect(await evaluate('document.querySelector(\'input[aria-label="GitHub webhook URL"]\').value')).toBe(endpoint);
  await ui("screenshot", "--out", `${fixture.logPath}.github-editor.png`);
  await evaluate('document.querySelector(\'input[aria-label="GitHub webhook URL"]\').scrollIntoView({ block: "center" })');
  await ui("screenshot", "--out", `${fixture.logPath}.github-config.png`);
  console.log(JSON.stringify({ uiEvidence: [`${fixture.logPath}.github-runs.png`, `${fixture.logPath}.github-editor.png`, `${fixture.logPath}.github-config.png`], routineId: routine.id, runId }));
}, 180_000);
